### ISSUE TITLE
Chapters 1-null and out of order

### ISSUE THREAD

**Issue by ddrabik** [Blanket-Warriors/BentoTime#25] opened 2016-03-16 02:22 UTC
# Description
In a book that has multiple chapters, they are listed out of order, one of the ranges is Null, and it should start at 1 instead of 0

# Steps to Reproduce
Navigate to any ChapterView with pages

# Expected:
Maybe the chapters should be individual pages instead of ranges? 
e.g. Pages 1, 2, 3

# Actual:
<img width="1045" alt="screen shot 2016-03-15 at 7 19 53 pm" src="https://cloud.githubusercontent.com/assets/884377/13800111/234675fc-eae3-11e5-8b21-48974bcb9908.png">

**Comment by ivebencrazy** [comment] 2016-03-16 06:01
This is not a bug, just a misinterpretation of data.  These are not ranges.  The Numbers on the right should be chapter titles.  Since these are (as seen) very inconsistent, though, this is something we need to address.

**Comment by ivebencrazy** [comment] 2016-04-15 06:56
Fixed in https://github.com/Blanket-Warriors/BentoTime/pull/32.

**Closed by ivebencrazy** 2016-04-15 06:56 UTC
Labels: bug
